### ISSUE TITLE
Date / version mismatch

### ISSUE THREAD

**Issue by ghost** [mvslovers/brexx370#101]
I noticed this after installing the latest fix
It is quite irrelevant but confusing, I thought I still had an old version around.

Marco
![Cattura](https://user-images.githubusercontent.com/84972398/140613312-80721b70-78f8-4348-9418-6e29e645ce86.JPG)

**Comment by Peter-Jacob** [comment]
indeed strange. We will check!

**Comment by mgrossmann** [comment]
That should already be fixed. @DocDoom99  could you validate this with the latest release, please?

**Comment by DocDoom99** [comment]
If by latest version you mean the one available here:

https://github.com/mvslovers/brexx370/releases/download/V2R5M0/BREXX370_V2R5M0_FIX_01.zip

I think the inconsistency persists, see image.
![Immagine 2022-01-28 110804](https://user-images.githubusercontent.com/84972398/151528600-4ec40170-922d-48ee-8bf7-66ed10f66f9a.jpg)

This can be closed. I uninstalled BREXX and am not going to use it for the moment, thanks.

Marco

**Comment by Peter-Jacob** [comment]
Closed, changed in newer version
