### ISSUE TITLE
stdin, stdout and stderr stay allocated after executing a brexx exec.

### ISSUE THREAD

**Issue by robprins** [mvslovers/brexx370#111]
Hi,
I noticed that stdin, stdout and stderr stay allocated after executing a BREXX exec,
Is that deliberate (for performance) or a tiny bug?
This occurs in V2R5M3.
Cheers,
Rob

**Comment by mgrossmann** [comment]
Hi @robprins 

We have fixed this behavior, now. If BREXX is allocating any of the STD* allocations,
it will free it in the end. Please wait for the upcoming fix release.

Best, 
Mike

**Comment by robprins** [comment]
Hi Mike.
Thanks for fixing this issue.
When can i get the fix for MVS-TK5?
Cheers,
Ro

**Comment by mgrossmann** [comment]
Hi Rob,

we are currently doing some tests. So next weekend seems to be a good time to release a new loading library.

Best,
Mike
