### ISSUE TITLE
`DATE('U')` Unable to re-allocate 2726592993 bytes. 

### ISSUE THREAD

**Issue by mainframed** [mvslovers/brexx370#118]
I'm running all the tests in the /test folder and noticed one kept failing, testing the following rexx on a fresh tk5u3 I can recreate the issue:

my script (in `HERC01.EXEC(TEST)`):
```rexx
SAY DATE('W')
SAY DATE('U')
```

When i run this script with `rx test` I get the following:

```
Thursday
      2 *-* SAY DATE('U')
 realloc: Unable to re-allocate 2726592993 bytes. Memory allocated is 196608
      2 *-* SAY DATE('U')
 Error 61 running TEST, line 2: Memory reallocation failed.
```

**Comment by Peter-Jacob** [comment]
The problem has been re-produced. An invalid re-alloc in the error routine has been performed, which triggered an error in the error handling process.   
The problem has been cured and will be provided in the next fix-level release

**Comment by mainframed** [comment]
I just built the new version and now get a seperate issue (this is on TK5, MVS/CE and TK4-):

```
 Saturday
      2 *-* SAY DATE('U')
 Error 40.47 running HERC01.TEST.CNTL(TEST), line 2: invalid or missing output f
ormat "
```

**Comment by mainframed** [comment]
After testing it looks like none of these work:

```c
    else {
        if      (brxoptions[1]=='A') Lscpy(datestr, "XEUROPEAN");
        else if (brxoptions[1]=='B') Lscpy(datestr, "XGERMAN");
        else if (brxoptions[1]=='C') Lscpy(datestr, "XUSA");
        else if (brxoptions[1]=='E') Lscpy(datestr, "EUROPEAN");
        else if (brxoptions[1]=='G') Lscpy(datestr, "GERMAN");
        else if (brxoptions[1]=='U') Lscpy(datestr, "USA");
        else Lscpy(datestr, "XEUROPEAN");
    }
```
From:
https://github.com/mvslovers/brexx370/blob/520947c1c708ec0dc07cf913cf839ae5c1584a86/lstring/date.c#L280


`DATE('A')`:

```
      1 *-* DATE('A')
 Error 40.47 running HERC01.TEST.CNTL(TEST), line 1: invalid or missing output f
ormat "
```
And the rest:

```
Error: Invalid command name syntax
      1 *-* DATE('B')
        +++ RC(-3) +++
 Error: Invalid command name syntax
      2 *-* DATE('E')
        +++ RC(-3) +++
 Error: Invalid command name syntax
      3 *-* DATE('C')
        +++ RC(-3) +++
      4 *-* DATE('G')
 Error 40.47 running HERC01.TEST.CNTL(TEST), line 4: invalid or missing output f
ormat "
```

**Comment by Peter-Jacob** [comment]
I think there is a misunderstanding of what the code’s intention is.

    else {
        if      (brxoptions[1]=='A') Lscpy(datestr, "XEUROPEAN");
        else if (brxoptions[1]=='B') Lscpy(datestr, "XGERMAN");
        else if (brxoptions[1]=='C') Lscpy(datestr, "XUSA");
        else if (brxoptions[1]=='E') Lscpy(datestr, "EUROPEAN");
        else if (brxoptions[1]=='G') Lscpy(datestr, "GERMAN");
        else if (brxoptions[1]=='U') Lscpy(datestr, "USA");
        else Lscpy(datestr, "XEUROPEAN");
    }
 
It does not define an output format “A”, “B”, … it uses a default option setting, which says the default data format is: XUSA, XEUROPEAN, XGERMAN, etc.
This must be done by an OPTION COMMAND in your REXX:
 
       say options('date','XGERMAN')        
       say "xgerman "date()                 
       say options('date','usa')            
       say "usa     "date()                 
       say options('date','xusa')           
       say "xusa    "date()                 
       say options('date','GERMAN')         
       say "german  "date()                 
 
then you can omit the output format in the DATE() function. I suspect I have forgotten to document the feature.
 
Regards
 
Peter 
 

Von: Soldier of FORTRAN ***@***.***> 
Gesendet: Sonntag, 5. Mai 2024 03:12
An: mvslovers/brexx370 ***@***.***>
Cc: Peter-Jacob ***@***.***>; State change ***@***.***>
Betreff: Re: [mvslovers/brexx370] `DATE('U')` Unable to re-allocate 2726592993 bytes. (Issue #118)

 

After testing it looks like none of these work:

    else {
        if      (brxoptions[1]=='A') Lscpy(datestr, "XEUROPEAN");
        else if (brxoptions[1]=='B') Lscpy(datestr, "XGERMAN");
        else if (brxoptions[1]=='C') Lscpy(datestr, "XUSA");
        else if (brxoptions[1]=='E') Lscpy(datestr, "EUROPEAN");
        else if (brxoptions[1]=='G') Lscpy(datestr, "GERMAN");
        else if (brxoptions[1]=='U') Lscpy(datestr, "USA");
        else Lscpy(datestr, "XEUROPEAN");
    }

From:
https://github.com/mvslovers/brexx370/blob/520947c1c708ec0dc07cf913cf839ae5c1584a86/lstring/date.c#L280

DATE('A'):

      1 *-* DATE('A')
 Error 40.47 running HERC01.TEST.CNTL(TEST), line 1: invalid or missing output f
ormat "

And the rest:

Error: Invalid command name syntax
      1 *-* DATE('B')
        +++ RC(-3) +++
 Error: Invalid command name syntax
      2 *-* DATE('E')
        +++ RC(-3) +++
 Error: Invalid command name syntax
      3 *-* DATE('C')
        +++ RC(-3) +++
      4 *-* DATE('G')
 Error 40.47 running HERC01.TEST.CNTL(TEST), line 4: invalid or missing output f
ormat "

**Comment by Peter-Jacob** [comment]
> I just built the new version and now get a seperate issue (this is on TK5, MVS/CE and TK4-):
> 
> ```
>  Saturday
>       2 *-* SAY DATE('U')
>  Error 40.47 running HERC01.TEST.CNTL(TEST), line 2: invalid or missing output f
> ormat "
> ```

"U" is ambiguous it could be USA or UNIX. USA requires 3 characters. I will think about a change.
