### ISSUE TITLE
RXLIB/TCPSF.rexx is not working

### ISSUE THREAD

**Issue by adlerhorst77** [mvslovers/brexx370#122]
Illegal function call in line 132 TCPSF.rexx

**Comment by Peter-Jacob** [comment]
Sorry, I haven't seen it. Can you provide us with some more details? The error message, for example. My suspicion your user doesn't have admin rights, which are required for TCPSF. Can you please try it again with an admin user?

**Comment by adlerhorst77** [comment]
Hi Peter,
the error message is illegal function call. I corrected line 132 in TCPSF.rexx locally from

rrc=TCPcloseS(#fd) to

rrc=TCPclose(#fd)

and everything works perfectly!

**Comment by Peter-Jacob** [comment]
TCPSF has been corrected!
