### ISSUE TITLE
Duplicate Labels

### ISSUE THREAD

**Issue by mgrossmann** [mvslovers/brexx370#37]
Under BRexx/370, in certain instances, one is allowed to have multiple labels with same name (i.e., duplicate labels). It’s so blatant that I’m not sure as to whether this is a bug or a feature . However,
I am of the mind that most developers would want to be notified, if in fact, they’d coded duplicate labels in error. I can’t think of a reason for which a developer would code duplicate labels on purpose. So, I vote for notification (Informational? Warning?) as long as another pass over the source or tokens is not required to do so. I’ve written a small BRexx program to demonstrate a duplicate label scenario. And, as you can see the program performed flawlessly regardless of the proliferation of duplicate labels.

**Comment by mgrossmann** [comment]
I'll take a look at how z/os behaves at this point.

**Comment by Peter-Jacob** [comment]
BREXX accepts duplicate labels or procedures, but will never use the second or later versions of it. In fact, a recurring label will be ignored. After a code inspection, we decided to not touch it, as there are architectural impacts.
