### ISSUE TITLE
RxLib's RxMsg - Modification Request

### ISSUE THREAD

**Issue by reggiemack-310** [mvslovers/brexx370#50]
[BRexx370.RxLib's RxMsg Function.Modification Request.pdf](https://github.com/mgrossmann/brexx370/files/4364055/BRexx370.RxLib.s.RxMsg.Function.Modification.Request.pdf)

**Comment by Peter-Jacob** [comment]
Enhancement request accepted for V2R3M0, implemented under test

**Comment by Peter-Jacob** [comment]
implemented in V2R3M0,
