### ISSUE TITLE
BREXX on Moseley's MVS 3.8j

### ISSUE THREAD

**Issue by MarcoVerpelli** [mvslovers/brexx370#55]
Hello,
referring to what can be read in

https://groups.io/g/turnkey-mvs/topic/having_issues_transferring/75814971p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,75814971

I can report my experience with Jay Moseley's "distro" (downloaded and generated on July 27th)
Both by transferring the xmit file via IND$FILE and via card reader, I was unable to unpack it. 
I followed JM's July 13rd instructions.

TK4- to the rescue! No problems in transferring and unpacking.

What did I do then?

TK44-: I used the TSO command available in nje38v200 and transferred the new created xmit file to the PC

JM "distro": loaded the file in the card reader, submitted the job to unpack it, no problem!

I confirm that creating the files to be distributed with nje38v200 tools is the right way to follow to obtain maximum compatibility.

Thank you

Marco

**Comment by mgrossmann** [comment]
Thank you for this information.

**Comment by NicClouston** [comment]
I had no problem installing on Jay's installation apart from:
1 - there was no IND£FILE (there is now)
2 - the region size specified is excessive

**Comment by mgrossmann** [comment]
@MarcoVerpelli 

any update on this topic?

**Comment by mgrossmann** [comment]
No further response.
Issue will be closed.
