### ISSUE TITLE
Guide to porting C applications to MVS

### ISSUE THREAD

**Issue by adelosa** [mvslovers/brexx370#61]
I have just successfully installed BREXX370 on my TK4 Hercules system and look forward to building some useful things with it.
I really appreciate the work that you are doing in porting such utilities to the mainframe platform.
In my searching the internet it seems that you may be some of the few people with the knowledge to answer my question.

I personally would like to port Micropython (https://github.com/micropython/micropython) to MVS 3.8j. Micropython is designed to runs on very low spec hardware -- embedded systems so I figure that it should be possible to port to MVS 3.8. 

Before I attempt such a project, I wanted to ask people who have done this before..

* Is this a stupid idea? I have some C and assembler programming skills but I am no expert..
* Will it be too difficult because of the C compiler limitations.. MVS C library limitations
* What are the things I need to do?? Are there any docs around that provide details on how to tackle such a project?
* Where do you seek support when you get stuck?

I will be documenting the journey for the benefit of others in the future looking to port applications..
Any assistance you can provide will be appreciated.
Anthony

**Comment by mainframed** [comment]
I would take a look at the jcc repo: https://github.com/mvslovers/jcc once you clone it there's an html folder full of documentation and API. 

I would then take a look at the `build` folder to see how brexx370 is built. Your first step would be to compile it with jcc on linux/windows.

**Comment by adelosa** [comment]
OK.. great.. thanks for the advice.. will check it out!

**Comment by mainframed** [comment]
I would also check this video, but if you're on tk4- you need to change the device to `20C` i believe.

https://www.youtube.com/watch?v=GV-dWA5Flec

**Comment by adelosa** [comment]
Thanks for that link.. Very helpful. At this stage, just working out how to get the modules compiled on my own machine. At this point I am finding Micropython tricky because it is c99 and it seems like the compiler and pdbclib are c89.. Now looking at LUA as an alternative which is C89.. Have one module compiled now so will see if I can get the rest working..

**Comment by mgrossmann** [comment]
@adelosa is that you? HackerSmacker#8496

**Comment by mainframed** [comment]
@adelosa there's been active discussion about LUA/370 and successful compilation on the moshix discord softwaredev channel: https://discord.gg/CckdrW

**Comment by adelosa** [comment]
Apologies for the delayed response.. really appreciate your comments.
@mgrossmann  No.. Am not HackerSmacker#8496 but love the name.. 
@mainframed I would love to join that Discord chat but the invite has expired.. any idea how to get a fresh one..
I can see why they have worked on LUA.. its stock C89 and seems to compile clean without issue.. The challenge I am having is with some of the larger modules that basically bomb JCC both on the PC and Mainframe.. I am guessing that MVS/380 is the answer to that issue.. just a guess.

**Comment by mgrossmann** [comment]
Hi Anrhony....

all fine... Please try this link:

https://discord.gg/bGAVYz

Regarding Lua and JCC. As far as I know, it is compiling just fine with JCC.


Mike
