### ISSUE TITLE
Receiving and Error 51 when main script calls function script from same library

### ISSUE THREAD

**Issue by JayMoseleyTX** [mvslovers/brexx370#78]
Using V2R3M0, when a script issues a call to an external function script, which is contained in the same library, I am receiving an invalid function name error (Error 51). I received this on a script that was functioning properly in the prior release. I created a simple main and sub script to illustrate:

```rexx
/* test main script calling external function script in same library
   library=JAY01.EXEC
   main script=TESTMAIN
   external function script=TESTSUB                                   */
 
SAY 'Beginning JAY01.EXEC(TESTMAIN)';
 
SAY 'CALL testsub;';
CALL testsub 'parm for testsub';
 
SAY 'Returned from CALL testsub';
 
EXIT;
```

```rexx
 /* test main script calling external function script in same library
    library=JAY01.EXEC
    main script=TESTMAIN
    external function script=TESTSUB                                  */
  
 SAY 'Beginning JAY01.EXEC(TESTSUB)';
  
 PARSE ARG thisArg;
  
 SAY 'Parameter retrieved:' thisArg;
  
 RETURN;
```
![Screenshot_2020-11-26_11-02-41](https://user-images.githubusercontent.com/71410407/100377515-00090f80-2fd7-11eb-9dab-6bdd2f283dce.png)

**Comment by mgrossmann** [comment]
Hello Jay,

I will check this, tomorrow.

Ty for your patience.
-- 
Von Gmail Mobile gesendet

**Comment by mgrossmann** [comment]
Jay,

we found the problem and will fix it as soon as possible!

Mike

**Comment by mgrossmann** [comment]
Hello, Jay,

the bug is now fixed. 
A new load library will be uploaded [here](https://github.com/mvslovers/brexx370/releases/tag/V2R3M0), shortly. 

Thank you very much for reporting this error.

Keep on going and happy BREXXing :)

Mike

**Comment by Peter-Jacob** [comment]
Hello Jay,

 

We confirm the error. The fixed load libs can be downloaded:

 

BREXXV2R3M0-Fix1.zip (github.com) <https://github.com/mvslovers/brexx370/releases/download/V2R3M0/BREXXV2R3M0-Fix1.zip> 

 

Regards

 

Peter 

 

Von: JayMoseleyTX <notifications@github.com> 
Gesendet: Donnerstag, 26. November 2020 18:06
An: mvslovers/brexx370 <brexx370@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [mvslovers/brexx370] Receiving and Error 51 when main script calls function script from same library (#78)

 

Using V2R3M0, when a script issues a call to an external function script, which is contained in the same library, I am receiving an invalid function name error (Error 51). I received this on a script that was functioning properly in the prior release. I created a simple main and sub script to illustrate:

/* test main script calling external function script in same library
   library=JAY01.EXEC
   main script=TESTMAIN
   external function script=TESTSUB                                   */
 
SAY 'Beginning JAY01.EXEC(TESTMAIN)';
 
SAY 'CALL testsub;';
CALL testsub 'parm for testsub';
 
SAY 'Returned from CALL testsub';
 
EXIT;
 /* test main script calling external function script in same library
    library=JAY01.EXEC
    main script=TESTMAIN
    external function script=TESTSUB                                  */
  
 SAY 'Beginning JAY01.EXEC(TESTSUB)';
  
 PARSE ARG thisArg;
  
 SAY 'Parameter retrieved:' thisArg;
  
 RETURN;

 <https://user-images.githubusercontent.com/71410407/100377515-00090f80-2fd7-11eb-9dab-6bdd2f283dce.png>
