### ISSUE TITLE
Full screen refresh on a timer

### ISSUE THREAD

**Issue by x0rcy5t** [mvslovers/brexx370#88]
I have been using the full screen functions of MVS BREXX for a couple months and love it's ease of use, but it would be very nice to be able to return from a screen display after a set amount of time to, for example, show a splash screen, or update a dynamic display, instead of the default behavior of waiting for an action key.

**Comment by mgrossmann** [comment]
@x0rcy5t Thanks for using bREXX/370 and thanks for sharing your ideas. I'm not quiet sure the requested feature is possible. But @Peter-Jacob and I will discuss this, for sure.

**Comment by Peter-Jacob** [comment]
@Mike, I think we discussed this last year. It would be a TPUT NOWAIT with an internal timer that returns with a timer event once it expires. This event could be treated as if the user presses the enter key or a PF action key.

**Comment by mgrossmann** [comment]
Implemented in V2R5
