### ISSUE TITLE
Probable integer owerflow issue

### ISSUE THREAD

**Issue by DocDoom99** [mvslovers/brexx370#91]
Hello everyone,
this time I have a problem with BREXX.V2R4M0.CMDLIB(IPLDATE), specifically with the following line:

rmcttod = _adr (rmct () + 124)

as far as I can understand the value should be 4 bytes (unsigned) and it seems to me that it is silently converted to a signed integer and therefore the value in rmcttod is negative. From this point on, nothing makes sense anymore. As a result I get a future IPL date and a negative uptime! The real uptime reported e.g. by DUPTIME is > 36 days.

Marco

**Comment by Peter-Jacob** [comment]
Marco, please do me a favour, send me the content of rmcttod (= _adr (rmct () + 124)). I need to see which number it is. According to your investigation, it must be a negative number, but I wonder how this possibly can be,

**Comment by DocDoom99** [comment]
tickfactor=1.024                /* RMCT time ticks a bit slower       */
rmcttod=_adr(rmct()+124)        /* pick start time                    */
say rmcttod /* <<<---- */
iplsec=RMCTTOD%1000*tickfactor  /* Convert into secs and mult. factor */
ipldays=iplsec%86400            /* days MVS is running                */
iplrem=iplsec//86400%1          /* remaining seconds                  */
days1900=Rxdate('b')-ipldays    /* calculate days since 1.1.1900      */
ipldate=Rxdate(,days1900,'B')   /* convert it back normal date        */
iplwday=Rxdate('WEEKDAY',days1900,'B') /* convert it back normal date */
cursec=time('s')-iplsec
do while cursec<0
   cursec=cursec+86400
end
say 'Current Time 'time('L')
say 'IPL on       'iplwday' 'ipldate' at 'sec2time(cursec)
say 'MVS up for   'ipldays' days 'sec2time(iplrem)' hours'
exit
/* ---------------------------------------------------------------------
 * address some mvs control blocks
 * ---------------------------------------------------------------------
 */
cvt:  return _adr(16)
rmct: return _adr(cvt()+604)
_adr: return c2d(storage(d2x(arg(1)),4))  /* return pointer (decimal) */

 READY
rx ipldate
 -1248752839
 Current Time 16:15:04.659172
 IPL on       Sunday 27/06/2021 at 71:27:06
 MVS up for   -14 days 19:12:-2 hours
 READY
duptime
 SYSTEM TK4- HAS BEEN UP FOR  36 DAYS 02:28:45
 READY

**Comment by Peter-Jacob** [comment]
The problem arises from treating an unsigned integer as an integer. If the integer exceeds the maximum of +2,147,483,647 it turns into a negative number.  In BREXX V2R5M0 is a **c2U()** function integrated, which returns the unsigned integer as a numeric string. You can use the numeric string in calculations, then it is internally converted into a float number.
